/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120255-g35a6de137a-20250714"
#endif /* AVUTIL_FFVERSION_H */
